#!/usr/bin/zsh -efu

file=$1
shift

while :; do
  go_on=false
  for t n in $(dce-names $file); do
    if dce-process dce-process-automatic $file $t $n; then
      go_on=true
    fi
  done
  $go_on || break
done

exec "$@"
