#!/usr/bin/zsh -efu

git diff

print -f "\n>>> remaining matches:\n"
dce-grep --heading || :
print '>>> (c)ommit / (e)dit / (s)skip / (w)rite commit msg? '
read -u 0 action
case $action in
S)
  print "starting an interactive shell.  will resume when it exits."
  $SHELL -i
  exec dce-prompt
;;
a)
  exec dce-prune automatic true
;;
c)
  dce-commit -F
  ;;
e)
  ${VISUAL:-vim} $file </dev/tty
  exec dce-prompt
  ;;
s)
  git checkout -f
  ;;
w)
  dce-commit -t
  ;;
*)
  print -f "GOT %s" "$action"
  exec dce-prompt
  ;;
esac
